### ISSUE TITLE
这个库是干啥用的

### ISSUE THREAD

**Issue by SnrtIevg** [SamJige/FindRESTUrl#1]
是用来替换 mrmanzhaow/RestfulToolkit 的吗？

**Comment by SamJige** [comment]
也不能说是替换 是写个类似功能的 正在考虑做 只有搜url功能的插件

**Comment by SamJige** [comment]
主要是RestfulToolkit 老是不更新 不知道是否是作者不维护了

**Comment by SnrtIevg** [comment]
有什么开发计划吗？我也想尝试参与一下， 不知道作者大大要人吗

**Comment by SamJige** [comment]
基本功能已经开发完成了 欢迎增加功能 
界面比较丑 有兴趣可以帮我优化一下  
因为是开源的 内容详见代码

**Comment by SamJige** [comment]
插件提交在 https://plugins.jetbrains.com/plugin/14360-findresturl
